language: objective-c
xcode_project: Calculator/Calculator.xcodeproj # path to your xcodeproj folder
xcode_scheme: CalculatorTests

before_install:
  - brew install tailor
script:
  - tailor Calculator
